### ISSUE TITLE
"unconfirmedBalance" broken

### ISSUE THREAD

**Issue by Levino** [bitpay/bitcore-node#363]
Hey there,

I am testing the "/api//addr/xxx" endpoint.

There are two balances, "confirmed" and "unconfirmed". The current implementation (undocumented, as far as I can tell) makes no sense.

- When an address has a confirmed balance of x > 0, and an unconfirmed transaction is spending x, then the unconfirmed balance will be 0, the confirmed will be x. -> I will take the unconfirmed balance for my app, when I want to handle 0 confirmation transactions (not the sum of both, which will give a wrong value!)

- When an address has a confirmed balance of x > 0 and an unconfirmed transaction adding y > 0 to the address, the confirmed balance will be x and the unconfirmed balance will be y. So the correct value for a balance, including all unconfirmed txs will be the sum (unconfirmed balance + confirmed balance).

- When an address has a confirmed balance of x > 0 and no unconfirmed transactions affecting it, the confirmed balance wil be x, the unconfirmed will be 0. So in this case the correct value is confirmed balance (The opposite of scenario 1).

My personal favorite for a new behaviour would be:

- Confirmed balance: "The balance of the address including all confirmed transactions"

- Unconfirmed balance: "The balance of the address including all confirmed AND unconfirmed transactions"

As far as I can tell one just has to remove the "else" here:

https://github.com/bitpay/bitcore-node/blob/02620a5b47b620dbff61baa84f8d66abc91edd37/lib/services/address/index.js#L1455

What do you say?

Be warned, this will break insight-api (or more precisly fix it, but maybe people have workarounds in place)

**Comment by braydonf** [comment]
Related: https://github.com/bitpay/bitcore-node/issues/340

**Comment by braydonf** [comment]
The existing behavior is there to be compatible with insight. We should look into the first scenario described.

I think it would be good, when we have a chance, to design it so that it's difficult for there to be any ambiguity. For example, what does "confirmed" mean? I think it could be much more clear to have `getBalance` _(and related)_ accept an integer argument with the number of confirmations. So if 6 was used, it would query the balance and not include the six most recent blocks. Likewise, if 0 was used the balance would include transactions in the mempool, and with 1 it would include the most recent block.

**Comment by Levino** [comment]
Yeah, but then unconfirmed has to negative when an unconfirmed transaction is spending funds. This is all really messy. Already the insight api is broken in this regard. Whatever way you look at it, the current situation is a bug (as you cannot figure out what is going on with the query result). The key value pair in the endpoint should either be removed or fixed asap. The current "official version" is misleading and dangerous.

**Comment by ChesTaylor** [comment]
Having the unconfirmed balance be the sum of the confirmed and unconfirmed funds is *more* misleading than the current system. The "unconfirmed balance" should be that part of the funds at an address which has 0 confirmations, not just a conglomeration of all of the funds at an address.

That confirmed and unconfirmed balance do not change due to an unconfirmed spend is a bit troublesome; a couple of fixes come to mind:
- Simply subtract the amount being spent (fees, change, the whole shebang) from the confirmed balance, so that "balance" or "balanceSat" reflect how much can safely be spent from that address. This is the balance you get if you sum the utxos at the given address after a spend.
- Have "unconfirmedBalance" and "unconfirmedBalanceSat" gain negative values when funds are spent from an address, so that the total spendable balance is still easily determinable by a single arithmetic operation, but there is still a distinct separation between those funds at the address with confirmations, and the change to those funds once some transactions get confirmed.

**Comment by Levino** [comment]
> Having the unconfirmed balance be the sum of the confirmed and unconfirmed funds is more misleading than the current system.

Please explain why this is misleading. What is the difference to the taking the sum as you suggest? If the unconfirmed balance is defined as "the balance including all unconfirmed transactions", I do not see any possible confusion.

**Comment by ChesTaylor** [comment]
The terms "confirmed balance" and an "unconfirmed balance" suggest mutual exclusivity. "Unconfirmed balance" I take to mean "the balance which is not confirmed." Hence my claim that including confirmed funds in "unconfirmed balance" would be misleading.

If I wanted "the balance including all unconfirmed transactions," I would call it something like "confirmation-independent balance" or maybe just "total balance." Even with separate and mutually exclusive "confirmed" and "unconfirmed" balances, the "total" should be easily attainable with a single simple addition operation (bearing in mind the original bug you pointed out, that spending funds does not subtract from confirmed OR unconfirmed balance).

**Comment by Levino** [comment]
Dear @ChesTaylor don't get me wrong, but you sound more like a grammar teacher than a developer. Let us leave out the wording for a second and let us talk about use cases.

My use case is pretty clear: I want to know at any point in time how much satoshis can be spent from an address with a single query. For this a value that gives the balance of an address calculated by taking all confirmed and unconfirmed transactions is the value that I need.

Please describe a use case, in which one has the need for the "balance" that can be calculated from taking only the unconfirmed transactions into account.

Coming back to the question of wording. If the "unconfirmed balance" is the sum of all the outputs minus the sum of all the inputs for the address, then the value can be negative. So it is not an absolute, but a relative value. Maybe it should then be named "unconfirmedBalanceRelativeToConfimedBalance"....

**Comment by ChesTaylor** [comment]
Here's my use-case:
There is an account composed of several addresses. I want to accumulate all of the unconfirmed-only funds in that account so I can display the funds which are pending separately from those which the network has verified via confirmations.

And I think "unconfirmed balance" is a fine name for what I want.

**Comment by Levino** [comment]
I understand @ChesTaylor what if "confirmed" funds have been spent from the addresses that you are monitoring? Say 1 BTC is confirmed and an unconfirmed transaction is spending this 1 BTC. What should your "pending funds" look like?

**Comment by ChesTaylor** [comment]
The "pending funds" would show the amount being spent as a negative value; "unconfirmedBalanceRelativeToConfimedBalance", as you put it previously. So, to use your example case, there would be 1 BTC in confirmed balance, and -1 BTC in unconfirmed balance.

blockr.io does something similar, showing what the net change in an address' confirmed balance will be once transactions gain confirmations.

**Comment by Levino** [comment]
But the insight api would show "0" as unconfirmed balance, not "-1". This is what this here is all about!

**Comment by ChesTaylor** [comment]
And we have never been in disagreement about that bug :n)

**Comment by Levino** [comment]
@ChesTaylor Alright :) Problem solved. I do not care how this is going to be fixed. As long as it is consitent. I can do confirmedBlance + unconfirmedBalance.

**Comment by ChesTaylor** [comment]
:+1:

**Comment by Levino** [comment]
Seems to have been fixed without me noticing. Problem is "solved" as in: One can work around this now. See here: #391
